// action constant types
export const SET_REMOVE_SELECTED_ROW = 'SET_REMOVE_SELECTED_ROW';
export const SET_REMOVE_GOVERNOR = 'SET_REMOVE_GOVERNOR';
export const SET_REMOVE_SENSITIVITY_LEVELS = 'SET_REMOVE_SENSITIVITY_LEVELS';
