/**
 * === SEARCH RESULT PAGE ===
 *    Pagination, Checkbox
 *    Sorthing, Filtering
 * === SEARCH RESULT PAGE ===
 */
export const HANDLE_KEY_PRESS = 'HANDLE_KEY_PRESS';
export const SEARCH_HANDLE_INPUT = 'SEARCH_HANDLE_INPUT';
export const SEARCH_RESULT_REQUEST = 'SEARCH_RESULT_REQUEST';
export const SEARCH_RESULT_SUCCESS = 'SEARCH_RESULT_SUCCESS';
export const SEARCH_RESULT_FAILURE = 'SEARCH_RESULT_FAILURE';
export const HANDLE_SEARCH_CLICK = 'HANDLE_SEARCH_CLICK';
export const HANDLE_SEARCH_CLOSE = 'HANDLE_SEARCH_CLOSE';
export const SET_REMOVE_SELECTED = 'SET_REMOVE_SELECTED';
export const SET_TOGGLE_SEARCH_CHECKBOX = 'SET_TOGGLE_SEARCH_CHECKBOX';
export const SET_TOGGLE_SEARCH_ALL_CHECKBOX = 'SET_TOGGLE_SEARCH_ALL_CHECKBOX';

/**
 * === SEARCH RESULT API RESULT ===
 *    Pagination, Checkbox
 *    Sorthing, Filtering
 * === SEARCH RESULT API RESULT ===
 */
