// POST /authenticate endpoint
export const AUTHENTICATE_FETCH = 'AUTHENTICATE_FETCH';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';
