// POST /authenticate endpoint
export const AUTHENTICATE_FETCH = 'AUTHENTICATE_FETCH';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE';

// POST /users/evaluate endpoint
export const USER_EVALUATE_FETCH = 'USER_EVALUATE_FETCH';
export const USER_EVALUATE_SUCCESS = 'USER_EVALUATE_SUCCESS';
export const USER_EVALUATE_FAILURE = 'USER_EVALUATE_FAILURE';
