// GET users/requests action
export const USER_REQUESTS_FETCH = 'USER_REQUESTS_FETCH';
export const USER_REQUESTS_SUCCESS = 'USER_REQUESTS_SUCCESS';
export const USER_REQUESTS_FAILURE = 'USER_REQUESTS_FAILURE';

// GET approver/requests action
export const APPROVER_REQUESTS_FETCH = 'APPROVER_REQUESTS_FETCH';
export const APPROVER_REQUESTS_SUCCESS = 'APPROVER_REQUESTS_SUCCESS';
export const APPROVER_REQUESTS_FAILURE = 'APPROVER_REQUESTS_FAILURE';

// GET governance/requests action
export const PENDING_REQUESTS_FETCH = 'PENDING_REQUESTS_FETCH';
export const PENDING_REQUESTS_SUCCESS = 'PENDING_REQUESTS_SUCCESS';
export const PENDING_REQUESTS_FAILURE = 'PENDING_REQUESTS_FAILURE';

// handling selected requests
export const SELECT_REQUEST = 'SELECT_REQUEST';
export const UNSELECT_REQUEST = 'UNSELECT_REQUEST';
