// GET users/requests action
export const USER_REQUESTS_FETCH = 'USER_REQUESTS_FETCH';
export const USER_REQUESTS_SUCCESS = 'USER_REQUESTS_SUCCESS';
export const USER_REQUESTS_FAILURE = 'USER_REQUESTS_FAILURE';

// GET archived/requests action
export const ARCHIVED_REQUESTS_FETCH = 'ARCHIVED_REQUESTS_FETCH';
export const ARCHIVED_REQUESTS_SUCCESS = 'ARCHIVED_REQUESTS_SUCCESS';
export const ARCHIVED_REQUESTS_FAILURE = 'ARCHIVED_REQUESTS_FAILURE';

// GET approver/requests action
export const APPROVER_REQUESTS_FETCH = 'APPROVER_REQUESTS_FETCH';
export const APPROVER_REQUESTS_SUCCESS = 'APPROVER_REQUESTS_SUCCESS';
export const APPROVER_REQUESTS_FAILURE = 'APPROVER_REQUESTS_FAILURE';

// GET governance/requests action
export const GOVERNANCE_REQUESTS_FETCH = 'GOVERNANCE_REQUESTS_FETCH';
export const GOVERNANCE_REQUESTS_SUCCESS = 'GOVERNANCE_REQUESTS_SUCCESS';
export const GOVERNANCE_REQUESTS_FAILURE = 'GOVERNANCE_REQUESTS_FAILURE';

// POST requests/decision action
export const REQ_DECISION_REQUEST_FETCH = 'REQ_DECISION_REQUEST_FETCH';
export const REQ_DECISION_REQUEST_SUCCESS = 'REQ_DECISION_REQUEST_SUCCESS';
export const REQ_DECISION_REQUEST_FAILURE = 'REQ_DECISION_REQUEST_FAILURE';

export const SET_TOGGLE_VIEW_CHECKBOX = 'SET_TOGGLE_VIEW_CHECKBOX';
export const SET_TOGGLE_VIEW_ALL_CHECKBOX = 'SET_TOGGLE_VIEW_ALL_CHECKBOX';

export const SET_TOGGLE_SENT_CHECKBOX = 'SET_TOGGLE_SENT_CHECKBOX';
export const SET_TOGGLE_SENT_ALL_CHECKBOX = 'SET_TOGGLE_SENT_ALL_CHECKBOX';

export const SET_TOGGLE_ARCHIVED_CHECKBOX = 'SET_TOGGLE_ARCHIVED_CHECKBOX';
export const SET_TOGGLE_ARCHIVED_ALL_CHECKBOX =
  'SET_TOGGLE_ARCHIVED_ALL_CHECKBOX';

// actions pertaining to filtering incoming request data
export const GET_ARCHIVED_REQUESTS = 'GET_ARCHIVED_REQUESTS';

//setFooterButtonClick
export const HANDLE_FOOTER_BUTTON_CLICK = 'HANDLE_FOOTER_BUTTON_CLICK';
