/**
 * === SEARCH RESULT PAGE ===
 *    Pagination, Checkbox
 *    Sorthing, Filtering
 * === SEARCH RESULT PAGE ===
 */
export const SEARCH_RESULT_PAGE_LOAD = 'SEARCH_RESULT_PAGE_LOAD';
export const SEARCH_HANDLE_INPUT = 'SEARCH_HANDLE_INPUT';
export const SEARCH_RESULT_REQUEST = 'SEARCH_RESULT_REQUEST';
export const HANDLE_KEY_PRESS = 'HANDLE_KEY_PRESS';
export const SEARCH_RESULT_SUCCESS = 'SEARCH_RESULT_SUCCESS';
export const SEARCH_RESULT_FAILURE = 'SEARCH_RESULT_FAILURE';
export const HANDLE_CHECKBOX_SELECT = 'HANDLE_CHECKBOX_SELECT';
export const HANDLE_SEARCH_CLICK = 'HANDLE_SEARCH_CLICK';
export const HANDLE_SEARCH_CLOSE = 'HANDLE_SEARCH_CLOSE';
export const SET_CLEAR_SELECTED_ASSETS = 'SET_CLEAR_SELECTED_ASSETS';
export const SET_TOGGLE_SEARCH_CHECKBOX = 'SET_TOGGLE_SEARCH_CHECKBOX';
export const SET_TOGGLE_SEARCH_ALL_CHECKBOX = 'SET_TOGGLE_SEARCH_ALL_CHECKBOX';
/**
 * === REQUEST ASSETS PAGE ===
 *    Table, Justification
 *    Requested For, Requesting For
 * === REQUEST ASSETS PAGE ===
 */
export const REQUEST_ASSETS_CLICK = 'REQUEST_ASSETS_CLICK';
export const REQUEST_CHECKBOX_SELECT = 'REQUEST_CHECKBOX_SELECT';
export const GET_EMPLOYEES_FETCH = 'GET_EMPLOYEES_FETCH';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const GET_EMPLOYEES_FAILURE = 'GET_EMPLOYEES_FAILURE';
export const HANDLE_SELECTED_EMPLOYEES = 'HANDLE_SELECTED_EMPLOYEES';
export const HANDLE_MODAL_TOGGLE = 'HANDLE_MODAL_TOGGLE';
export const MAKE_REQUESTS_FETCH = 'MAKE_REQUESTS_FETCH';
export const MAKE_REQUESTS_SUCCESS = 'MAKE_REQUESTS_SUCCESS';
export const MAKE_REQUESTS_FAILURE = 'MAKE_REQUESTS_FAILURE';
export const JUSTIFICATION_HANDLE_INPUT = 'JUSTIFICATION_HANDLE_INPUT';
export const SET_TOGGLE_ASSET_CHECKBOX = 'SET_TOGGLE_ASSET_CHECKBOX';
export const SET_TOGGLE_ASSET_ALL_CHECKBOX = 'SET_TOGGLE_ASSET_ALL_CHECKBOX';
export const HANDLE_REMOVE_SELECTED = 'HANDLE_REMOVE_SELECTED';
