// Action Types
const SENT_REQUESTS_FETCH = 'SENT_REQUESTS_FETCH';
const SENT_REQUESTS_SUCCESS = 'SENT_REQUESTS_SUCCESS';
const SENT_REQUESTS_FAILURE = 'SENT_REQUESTS_FAILURE';

export { SENT_REQUESTS_FAILURE, SENT_REQUESTS_FETCH, SENT_REQUESTS_SUCCESS };
